### ISSUE TITLE
Text integration tracking issue

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#1192]
A tracking issue, largely for my own benefit, detailing the various bits of work involved in incorporating the new piet text stuff into druid.

- [ ] a basic `TextLayout` component that can be used to draw simple text.
- [ ] expose max width and line breaking
- [ ] expose text alignment
- [ ] support in layout for indicating baseline positions, add baseline option to flex container
- [ ] Add a rich-text type based on xi-rope
- [ ] improve documentation (maybe a book chapter?) covering various text API use cases

**Comment by sysint64** [comment]
Probably known issue, but just in case - there are a lot of `TextAlignment not supported by cairo toy text` messages.

In my realtime system, the time needed to render a frame dropped from 1ms to 188ms because of that :(

**Comment by sysint64** [comment]
Oh well, that's funny, I have steady 6ms-10ms if I run from the terminal, but 188ms if I run from emacs.
